export const CREATE_NEW_CART = "CREATE_NEW_CART";
export const DELETE_CART = "DELETE_CART";
export const ADD_CART_PRODUCT = "ADD_PRODUCT";
export const DELETE_CART_PRODUCT = "DELETE_CART_PRODUCT";
export const UPDATE_CART_PRODUCT_COUNT = "UPDATE_CART_PRODUCT_COUNT";

export const ADD_CATEGORY = "ADD_CATEGORY";
export const SET_NAV_HEADER = "SET_NAV_HEADER";
export const CALCULATE_NUTRIENTS = "CALCULATE_NUTRIENTS";
export const GET_PRODUCT_HINTS = "GET_PRODUCT_HINTS";
export const CLEAR_PRODUCT_HINTS = "CLEAR_PRODUCT_HINTS";

export const CREATE_NEW_MEAL = "CREATE_NEW_MEAL";
export const DELETE_MEAL = "DELETE_MEAL";
export const ADD_MEAL_PRODUCT = "ADD_MEAL_PRODUCT";
export const DELETE_MEAL_PRODUCT = "DELETE_MEAL_PRODUCT";
export const UPDATE_MEAL_PRODUCT_COUNT = "UPDATE_MEAL_PRODUCT_COUNT";
